import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';

const Home: NextPage = function () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-red-400 text-3xl">Hello cpotify clone</h1>
      </main>
    </>
  );
};

export default Home;
